### ISSUE TITLE
Unexpected error while acquiring application default credentials

### ISSUE THREAD

**Issue by ofrobots** [googleapis/nodejs-logging-winston#115]
Originally reported by @opyate in https://github.com/googleapis/nodejs-logging-winston/issues/1#issuecomment-400619391.

@stephenplusplus I'll assume the role of the issue opener :-)

I'm auditing all our triggers using @google-cloud/logging-winston and the log events will seemingly randomly not appear in StackDriver.

Please see this example where the logger's event listener sees the log messages which ought to go to StackDriver (they don't):

<img width="1567" alt="screen shot 2018-06-27 at 10 56 45" src="https://user-images.githubusercontent.com/96808/41968096-4d01d2a2-79fb-11e8-8ae3-44159e6e349b.png">

...and then a little bit later in StackDriver you'll see the OP's error:

<img width="1573" alt="screen shot 2018-06-27 at 10 57 52" src="https://user-images.githubusercontent.com/96808/41968102-5241bb4c-79fb-11e8-9bc8-589341763b6a.png">

I'll try and put @ofrobots suggestion of a "wait to drain" at the end of each trigger, but this is obviously not a long-term solution.

**Comment by ofrobots** [comment]
@ofrobots commented in https://github.com/googleapis/nodejs-logging-winston/issues/1#issuecomment-400807870.

Hi @opyate. Thanks for the report and the detailed information. Based on the error, it seems that, for whatever reason, the code fails to identify the running environment to be GCF (or rather, GCP in general). This causes auth to fail with the above error.

To be able to debug this further, I think we need to make a change in dependent module (gcp-metadata) that is currently swallowing unexpected errors instead of bubbling them up. I'm trying to fix this in stephenplusplus/gcp-metadata#57, and once that gets released, it would good if you could try with the updated code. I want to know the precise reason why we were unable to identify your GCF running environment as lacking the metadata service.

I'll ping this thread once the modules have been updated with the necessary fix to debug this further.

**Comment by opyate** [comment]
@ofrobots 

My local `gcp-metadata` now has this block, which relates to your change:

```
                case 2:
                    err_1 = _a.sent();
                    // Failure to resolve the metadata service means that it is not available.
                    if (err_1.code && (err_1.code === 'ENOTFOUND' || err_1.code === 'ENOENT')) {
                        return [2 /*return*/, false];
                    }
                    // Throw unexpected errors.
                    throw err_1;
```

Upon updating the function, I now see this:

<img width="1558" alt="screen shot 2018-06-27 at 23 12 09" src="https://user-images.githubusercontent.com/96808/42002702-1cf6cb20-7a60-11e8-99cb-50c86ff624f7.png">

**Comment by opyate** [comment]
Stack traces.

The first one:

```
"Error: Could not load the default credentials. Browse to https://developers.google.com/accounts/docs/application-default-credentials for more information.
    at /user_code/node_modules/@google-cloud/vision/node_modules/google-auth-library/lib/auth/googleauth.js:316:21
    at /user_code/node_modules/@google-cloud/vision/node_modules/google-auth-library/lib/auth/googleauth.js:346:7
    at Request._callback (/user_code/node_modules/@google-cloud/vision/node_modules/google-auth-library/lib/transporters.js:70:30)
    at self.callback (/user_code/node_modules/@google-cloud/vision/node_modules/request/request.js:185:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestError (/user_code/node_modules/@google-cloud/vision/node_modules/request/request.js:877:8)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketErrorListener (_http_client.js:310:9)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at emitErrorNT (net.js:1296:8)
    at /user_code/node_modules/continuation-local-storage/node_modules/async-listener/glue.js:188:31
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickDomainCallback [as _tickCallback] (internal/process/next_tick.js:128:9)"  
```

The unexpected one:

```
"Error: Unexpected error while acquiring application default credentials: Could not load the default credentials. Browse to https://developers.google.com/accounts/docs/application-default-credentials for more information.
    at GoogleAuth.<anonymous> (/user_code/node_modules/google-auto-auth/node_modules/google-auth-library/build/src/auth/googleauth.js:248:31)
    at step (/user_code/node_modules/google-auto-auth/node_modules/google-auth-library/build/src/auth/googleauth.js:47:23)
    at Object.next (/user_code/node_modules/google-auto-auth/node_modules/google-auth-library/build/src/auth/googleauth.js:28:53)
    at fulfilled (/user_code/node_modules/google-auto-auth/node_modules/google-auth-library/build/src/auth/googleauth.js:19:58)
    at propagateAslWrapper (/user_code/node_modules/continuation-local-storage/node_modules/async-listener/index.js:502:23)
    at /user_code/node_modules/continuation-local-storage/node_modules/async-listener/glue.js:188:31
    at /user_code/node_modules/continuation-local-storage/node_modules/async-listener/index.js:539:70
    at /user_code/node_modules/continuation-local-storage/node_modules/async-listener/glue.js:188:31
    at process._tickDomainCallback [as _tickCallback] (internal/process/next_tick.js:135:7)"  
```

**Comment by opyate** [comment]
Just remembered that I wrote a post today about swallowing errors. Uncanny!

https://opyate.com/posts/2018-06-27-rethrow-errors-on-firebase

**Comment by ofrobots** [comment]
Did you also pick up this change in google-auth-library or is the above output without it: https://github.com/google/google-auth-library-nodejs/pull/394

**Comment by ofrobots** [comment]
So far, this doesn't make a lot of sense to me. The order of the errors seems strange.

The first error indicates that we detected that we were not running on Google Cloud – which would be odd since you _are_ running on Cloud Functions.

The even more strange thing is that I don't understand who prints the 'Could not ...' error. It should be caught by the second catch block [here](https://github.com/google/google-auth-library-nodejs/blob/b82d2c401089390813ee9edcda634ec14853e36e/src/auth/googleauth.ts#L243-L262).

**Comment by opyate** [comment]
> The even more strange thing is that I don't understand who prints the 'Could not ...' error. It should be caught by the second catch block here.

I've cloned/compiled `google-auth-library-nodejs` and have:

```
                    case 8:
                        _b.trys.push([8, 10, , 11]);
                        return [4 /*yield*/, this._checkIsGCE()];
                    case 9:
                        isGCE = _b.sent();
                        return [3 /*break*/, 11];
                    case 10:
                        e_2 = _b.sent();
                        throw new Error('Unexpected error determining execution environment: ' + e_2.message);
                    case 11:
                        if (!isGCE) {
                            // We failed to find the default credentials. Bail out with an error.
                            throw new Error('Could not load the default credentials. Browse to https://developers.google.com/accounts/docs/application-default-credentials for more information.');
                        }
                        // For GCE, just return a default ComputeClient. It will take care of
                        // the rest.
                        this.cachedCredential = new computeclient_1.Compute(options);
                        return [4 /*yield*/, this.getDefaultProjectId()];
                    case 12:
                        projectId = _b.sent();
                        return [2 /*return*/, { projectId: projectId, credential: this.cachedCredential }];
```

However, the `googleauth.js` in my project has:

```
                    case 8:
                        _b.trys.push([8, 13, , 14]);
                        return [4 /*yield*/, this._checkIsGCE()];
                    case 9:
                        gce = _b.sent();
                        if (!gce) return [3 /*break*/, 11];
                        // For GCE, just return a default ComputeClient. It will take care of
                        // the rest.
                        this.cachedCredential = new computeclient_1.Compute(options);
                        return [4 /*yield*/, this.getDefaultProjectId()];
                    case 10:
                        projectId = _b.sent();
                        return [2 /*return*/, { projectId: projectId, credential: this.cachedCredential }];
                    case 11: 
                    // We failed to find the default credentials. Bail out with an error.
                    throw new Error('Could not load the default credentials. Browse to https://developers.google.com/accounts/docs/application-default-credentials for more information.');
                    case 12: return [3 /*break*/, 14];
                    case 13:
                        e_2 = _b.sent();
                        throw new Error('Unexpected error while acquiring application default credentials: ' +
                            e_2.message);
                    case 14: return [2 /*return*/];
```

An extra conditional there in the recent code which probably explains the 2 errors. I deployed my functions again with both the latest `gcp-metadata` and `google-auth-library-nodejs`, and get no errors this time. 

However, log entries are still missing in StackDriver, even though the logging event handler shows I'm logging stuff.

**Comment by opyate** [comment]
I redeployed the function, waited 5 minutes, tested, and still no errors, but also still only one log entry makes it to StackDriver.

(5 minutes because I want the instances to throttle down. I've seen ECONNRESET w.r.t Redis every 4 minutes)

**Comment by dorshay6** [comment]
I have the same issue on GKE

**Comment by DominicKramer** [comment]
@ofrobots What is the status of this?  Thanks.

**Comment by DominicKramer** [comment]
@ofrobots Is this issue actionable, or is a test case still needed?

**Comment by ofrobots** [comment]
Since we don't have a test-case to reproduce, let's close this out. If a test-case becomes available, anyone can leave a comment here and we can re-open.

**Comment by mg-wtc** [comment]
I'm also experiencing this error; I have followed the instructions for setting up StackDriver with Winston here - https://cloud.google.com/logging/docs/setup/nodejs - I have a Cloud Function with a HTTP trigger which works fine, but deploying a Function with a PubSub trigger results in the error "Could not load the default credentials". I have replaced Winston with Bunyan using googleapis/nodejs-logging-bunyan, and logging is now working correctly.

**Comment by bcoe** [comment]
@mg-wtc the winston and bunyan libraries use the same underlying auth library, perhaps try:

```bash
rm -rf package-lock.json
rm -rf node_modules
```

And make sure that you're on the latest version of everything? If you continue to run into issues please let us know. I recommend opening a new issue, since this one was closed and a bit stale.
