### ISSUE TITLE
Label support for log entries

### ISSUE THREAD

**Issue by csombok** [googleapis/nodejs-logging-winston#20]
In our project we use the [basic logging client library](https://www.npmjs.com/package/@google-cloud/logging) currently though it seems a good idea switching to use Winston based package which is a better approach from configuration perspective.
Unfortunately there is a showstopper issue because [log entry labels ](https://cloud.google.com/logging/docs/reference/v2/rest/v2/entries/write)are not supported which is a handy feature in StackDriver logging enabling us to filter log entries.
Is it in the roadmap to provide a way for specifying labels in log entries via metadata?

![image](https://user-images.githubusercontent.com/12937212/34527879-58767206-f0a7-11e7-9636-713efd8bd3a6.png)

**Environment details:**
OS: Windows 8.1
Node.js version: 8.9.1
npm version: 5.5.1
version: 0.7.0

**Comment by ofrobots** [comment]
Hi @csombok. Today we report all winston reported metadata as a `metadata` property in the payload. I think what you are proposing is that we promote the `labels` property of the winston provided metadata to the `labels` property of the `LogEntry` message? That sounds reasonable, given that we already do such treatment for `httpRequest` property, if present in the winston provided metadata. This would be a semver major change, IMO.

**Comment by csombok** [comment]
Hi @ofrobots, Exactly, this would be my desire. :) This would make it fully customizable with StackDriver LogEntry. Thanks
