### ISSUE TITLE
Objects not logged to Stackdriver Log Viewer

### ISSUE THREAD

**Issue by MattGson** [googleapis/nodejs-logging-winston#277]
#### Environment details

  - OS: OSX 10.11
  - Node.js version: 8
  - npm version: ?
  - `@google-cloud/logging-winston` version: 0.10.2

#### Steps to reproduce

```js
const gceWinston = new LoggingWinston({
    serviceContext: {
        service: 'km-api-service',
        version: 'versionX'
    },
    projectId: 'id',
    label: 'Global'
});



const Winston = createLogger({
       format: combine(
            errors({ stack: true }),
            timestamp({
                format: 'YYYY-MM-DD HH:mm:ss'
            }),
            json()
        ),
        level: config.logLevel,
        defaultMeta: {service: 'api-service'},
        transports: [gceWinston]
 });

```

```js
_logger.debug('Message data: %o', data);
_logger.info('Message data: %j', data);
_logger.info(data);
```

![Screen Shot 2019-03-11 at 7 52 33 PM](https://user-images.githubusercontent.com/20088009/54105227-4f8c5e00-4437-11e9-915a-f5a9beddc597.png)

Logging locally to the console works as expected but when logging to StackDriver, objects do not show.

Edited(Dominic Kramer):  Enabled syntax highlighting.

**Comment by MattGson** [comment]
Looks like I just needed to add the splat() formatter.

**Comment by aaronhong** [comment]
How did you get it to work?

I've tried this and it doesn't work for me:
```
  logger.add(new LoggingWinston({
    format: logFormat.combine(
      logFormat.splat(),
      logFormat.simple()
    ),
    level: logLevel || 'info'
  }))
```

Dependencies
- "@google-cloud/logging-winston": "^3.0.0"
- "winston": "^3.2.1"
