### ISSUE TITLE
TS shows an error with express middleware

### ISSUE THREAD

**Issue by delphinus** [googleapis/nodejs-logging-winston#341]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

Please run down the following list and make sure you've tried the usual "quick fixes":

  - Search the issues already opened: https://github.com/googleapis/nodejs-logging-winston/issues
  - Search the issues on our "catch-all" repository: https://github.com/googleapis/google-cloud-node
  - Search StackOverflow: http://stackoverflow.com/questions/tagged/google-cloud-platform+node.js

If you are still having issues, please be sure to include as much information as possible:

#### Environment details

  - OS: macOS Mojave 10.14.5
  - Node.js version: 12.4.0
  - npm version: 6.9.0
  - `@google-cloud/logging-winston` version: 1.0.0

#### Steps to reproduce

* I created a minimal repo to reproduce: https://github.com/delphinus/logging-winston-test

  1. Write minimal TS to use express middleware.

   ```typescript
   import express from 'express'
   import * as lw from '@google-cloud/logging-winston'
   
   const app = express()
   
   ;(async () => {
     const { mw } = await lw.express.middleware()
     app.use(mw)
     app.get('/', (req, res) => {
       (req as any).log.info('this is log')
       res.status(200).send('Hello, World!').end()
     })
   })()
   ```

  2. compile

   ```sh
   npx tsc
   ```

  3. Shows an error

   ```typescript
   node_modules/@google-cloud/logging-winston/build/src/index.d.ts:85:45 - error TS2507: Type 'typeof TransportStream' is not a constructor function type.

   85 export declare class LoggingWinston extends TransportStream {
                                                  ~~~~~~~~~~~~~~~


   Found 1 error.
   ```

**Comment by ofrobots** [comment]
I believe this is ultimately a problem with TypeScript's `esModuleInterop` flag. There is no value of the flag we can set on our side that makes all our users happy :(.

Is it possible for you to not use `esModuleInterop`?

Related: https://github.com/googleapis/nodejs-logging-bunyan/issues/241

**Comment by JustinBeckwith** [comment]
FWIW - we've usually found the problem arrises when downstream dependencies are using `esModuleInterop`.  Where does `TransportStream` come from?  Is it possible the types for `Winston` are using `esModuleInterop`?

**Comment by delphinus** [comment]
@ofrobots I see it fixes this by using `esModuleInterop: false` & CommonJS style require.

https://github.com/delphinus/logging-winston-test/pull/1

I will fix my code base to use this way -- `esModuleInterop: false`, but is this a usual way on Google side? I have been using `esModuleInterop: true` all the time after [TS introduced this option in 2.7][ts].

[ts]: https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-7.html#support-for-import-d-from-cjs-from-commonjs-modules-with---esmoduleinterop

ES module style (`import express from 'express'`) is more TS-way than CommonJS style (`import express = require('express')`) and MS highly recommends that. Is it difficult to convert this repo to use it?
