### ISSUE TITLE
Express middleware logging issue

### ISSUE THREAD

**Issue by daaain** [googleapis/nodejs-logging-winston#343]
#### Environment details

  - OS: Debian (using `node:10.15.0` Docker image)
  - Node.js version: v10.15.0
  - npm version: 6.4.1 (using yarn 1.12.3 though)
  - `@google-cloud/logging-winston` version: 1.0.0

#### Steps to reproduce

  1. Set up Express middleware
  2. Make request

Expected outcome: parent request log entry gets created and log entries are bundled

Actual outcome: parent request log entry looks misconfigured (doesn't have trace) and subsequent logs are not bundled

Screenshot of the problem:

<img width="872" alt="image" src="https://user-images.githubusercontent.com/69962/59507854-31098900-8ea4-11e9-9255-4d0c4c44de42.png">

As a side note the severity levels are off for some reason too...

I think the issue might be that the logger is called with the metadata object as message? See: https://github.com/googleapis/nodejs-logging-winston/blob/master/src/middleware/express.ts#L74

**Comment by ofrobots** [comment]
Thanks @daaain. Your analysis was correct, thanks! Fix over in #349.
