### ISSUE TITLE
lw.express.makeMiddleware is not a function

### ISSUE THREAD

**Issue by EdByrnee** [googleapis/nodejs-logging-winston#379]
Following the instructions in the ReadMe for the express middleware:

```javascript
module.exports = async function(){
  
  const {mylogger, mw} = await lw.express.makeMiddleware(logger);
  return mw;
} 
```

But it says makeMiddlware doesn't exist?

`UnhandledPromiseRejectionWarning: TypeError: lw.express.makeMiddleware is not a function`

**Comment by zerefel** [comment]
I think they're just about to release v2.0.0, which changes `lw.express.middleware` to `lw.express.makeMiddleware`. You can use `lw.express.middleware` until 2.0.0 lands or its PR branch https://github.com/googleapis/nodejs-logging-winston/tree/release-v2.0.0.

I am not a contributor and these are my observations.

**Comment by EdByrnee** [comment]
> https://github.com/googleapis/nodejs-logging-winston/tree/release-v2.0.0

yeah, you're right thanks not quite sure how to build so will wait for release

**Comment by zerefel** [comment]
It would be nice if we could get a pre-release for testing purposes.

**Comment by EdByrnee** [comment]
Any ETA on the update?

**Comment by JustinBeckwith** [comment]
@ofrobots thoughts on getting this out?

**Comment by soldair** [comment]
https://github.com/googleapis/nodejs-logging-winston/blob/master/src/middleware/express.ts#L33
seems to be out
