### ISSUE TITLE
Cut 2.0.0 release

### ISSUE THREAD

**Issue by ofrobots** [googleapis/nodejs-logging-winston#380]
While the [2.0.0 release PR](https://github.com/googleapis/nodejs-logging-winston/pull/365) is open, it is not quite optimal from the release notes point of view. For semver majors, it is important that the release notes communicate clearly what is breaking. I pushed a commit with [a better changelog](https://github.com/googleapis/nodejs-logging-winston/commit/443ee2310e7eaaa1c14e21d3f7e4d13e0bb27261), but that got overwritten by the release automation.

How do we do a release with proper release notes?

**Comment by bcoe** [comment]
@ofrobots the only part of the CHANGELOG that's used for the regex when finding the last release that occurred is:

```
## 2.0.0
```

So after release I'd just manually edit the contents of the CHANGELOG and release; alternatively, you can do so on the release branch before landing more features.

**Comment by bcoe** [comment]
@ofrobots happy to sync up with you tomorrow to make sure the release goes smoothly :+1:

**Comment by ofrobots** [comment]
I am ooo for the rest of the week. We can sync on Monday. Or if someone
else want to push a release in the meanwhile, feel free.

**Comment by EdByrnee** [comment]
Hi all do we have an ETA for v2 release

**Comment by bcoe** [comment]
@EdByrnee 👋 `2.x` is out the door, thanks to @soldair.
