### ISSUE TITLE
Why do we need this library if console.log can also write to stackdriver?

### ISSUE THREAD

**Issue by chaoyangnz** [googleapis/nodejs-logging-winston#393]
**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

Hi,

I am quite confused. I have an application deployed in GKE and i use `winston` to write to Console. I can get the logs in stackdriver.

So why do I need this library?

**Comment by soldair** [comment]
You don't need this library if the data console.log is sending is enough for you.

this library helps you send structured data to *any* log name in stackdriver which you might not get with only standard out. For example sending logs only related to purchasing to a "purchase" log
