### ISSUE TITLE
GA release

### ISSUE THREAD

**Issue by JustinBeckwith** [googleapis/nodejs-logging-winston#413]
Package name: `@google-cloud/logging-winston`
Current release: **beta**
Proposed release: **GA**

## Instructions

Check the lists below, adding tests / documentation as required. Once all the "required" boxes are ticked, please create a release and close this issue.

## Required

- [x] 28 days elapsed since last beta release with new API surface
- [x] Server API is GA
- [x] Package API is stable, and we can commit to backward compatibility
- [x] All dependencies are GA

## Optional

- [x] Most common / important scenarios have descriptive samples
- [ ] Public manual methods have at least one usage sample each (excluding overloads)
- [ ] Per-API README includes a full description of the API
- [ ] Per-API README contains at least one “getting started” sample using the most common API scenario
- [ ] Manual code has been reviewed by API producer
- [ ] Manual code has been reviewed by a DPE responsible for samples
- [ ] 'Client LIbraries' page is added to the product documentation in 'APIs & Reference' section of the product's documentation on Cloud Site

**Comment by DominicKramer** [comment]
@bcoe Is there something blocking the GA launch or should we launch GA?  It is fine either way.  I just want to make sure it is document here.  Thanks.

**Comment by bcoe** [comment]
@DominicKramer I'm comfortable with us calling things GA :+1:

**Comment by DominicKramer** [comment]
Sounds good.  Do you want to create a release updating this to GA, or do you want me to do it?

**Comment by bcoe** [comment]
@DominicKramer if you have a moment to do so, and are able to run `synthtool` in the project to make sure we update the README too, I probably won't be able to get to this until a bit later in the week.

**Comment by DominicKramer** [comment]
@bcoe I was reading through the release playbook, and since I don't have permission to even start the release process, it is probably faster if you just create the release since you probably already have all the permissions needed.  Making the release at the end of this week is not a problem.

**Comment by JustinBeckwith** [comment]
This is done :)
