### ISSUE TITLE
gprc leaves open handles when testing with Jest

### ISSUE THREAD

**Issue by jmolero** [googleapis/nodejs-logging-winston#414]
Importing the transport causes jest to report the following open handle as mentioned in #389 by @dan-turner:

```
Jest has detected the following 1 open handle potentially keeping Jest from exiting:

  ●  Timeout

      at new SubchannelPool (node_modules/@grpc/grpc-js/build/src/subchannel-pool.js:38:13)
      at Object.<anonymous> (node_modules/@grpc/grpc-js/build/src/subchannel-pool.js:99:30)
```

#### Environment details

  - OS: macOS Catalina (10.15.1)
  - Node.js version: 10.16.0
  - npm version: 6.9.0
  - `@google-cloud/logging-winston` version: 3.0.0

#### Steps to reproduce

  1.  This is how I set it up:
```
import winston from 'winston';
import { LoggingWinston } from '@google-cloud/logging-winston';
import cfg from '../../cfg/winston';

const loggingWinston = new LoggingWinston(cfg);

const logger = winston.createLogger({
    level: 'info ',
    exceptionHandlers: loggingWinston,
    transports: [
        // Add Stackdriver Logging
        loggingWinston,
    ],
});

export default logger;
```

**Comment by bcoe** [comment]
@murgatroid99 @alexander-fenster any chance this is related to some of the upstream patches we're testing in `@grpc/grpc-js`?

**Comment by murgatroid99** [comment]
This looks like grpc/grpc-node#1080. The fix suggested for that is out in version 0.6.11, but that only really fixes things if channels are explicitly closed.

I do believe that this is also a bug in Jest. The timer in question is unrefed, which should mean that it does not hold the process open.

**Comment by dan-turner** [comment]
Even just importing the logger (and never even new'ing one up) is enough to cause the open handle problem:

`import { LoggingWinston } from '@google-cloud/logging-winston';`

**Comment by bcoe** [comment]
@alexander-fenster I think there's a chance this is actually related to our auth library, which tries to fetch the project name from the metadata server, even if the metadata server is not available.

**Comment by soldair** [comment]
does this still happen? i know grpc has had improvements in more recent versions we use in the library. please reopen if the issue still exists

**Comment by vpontis** [comment]
@soldair I am still getting this issue with grpc + supertest. 

I can try to come up with a minimal repro if that would be helpful :)

**Comment by techieshark** [comment]
Seeing the same thing:

> Jest has detected the following 1 open handle potentially keeping Jest from exiting:

>  ●  Timeout

>      at Object.<anonymous> (node_modules/@grpc/grpc-js/src/server-call.ts:326:33)
>      at Object.<anonymous> (node_modules/@grpc/grpc-js/src/server.ts:26:1)

Using latest version of grpc-js, 0.6.18

**Comment by the21st** [comment]
This is still an issue for me even with Jest 25

**Comment by azban** [comment]
currently working around this by clearing the timeout causing the open handle after each test suite.

i'm running the following script via `setupFilesAfterEnv` via the jest config. https://gist.github.com/azban/8f559080c9bd0835d8a0b64b1dbcb631

**Comment by lokoArt** [comment]
@grpc/grpc-js has the issue...

**Comment by ankurverma1994** [comment]
Any update on the issue? Still getting issue with Jest
```
Timeout

      at Object.<anonymous> (node_modules/@google-cloud/logging/node_modules/@grpc/grpc-js/src/server-call.ts:344:33)
```

**Comment by johonIngka** [comment]
I have experienced an issues with Jest throwing a warning when using the lib @google-cloud/logging-winston. 

"Jest did not exit one second after the test run has completed.

'This usually means that there are asynchronous operations that weren't stopped in your tests. Consider running Jest with `--detectOpenHandles` to troubleshoot this issue.
"

For some reason, adding a projectId to my LoggingWinston config seems to do the trick for me. If PROJECT_ID is not set I get the warning. If i set it Jest does no longer complain. The other env variables in the config does not seem to have any influence. Only PROJECT_ID seems to matter. 

const winstonLogger = new LoggingWinston({
  projectId: process.env.PROJECT_ID,
  serviceContext: {
    service: process.env.TRACING_BOX_NAME,
  },
  defaultCallback: (err) => {
    if (err) {
      console.log('Error occured: ' + err);
    }
  },
});
