### ISSUE TITLE
Affected by GCP deprecation of activity logs?

### ISSUE THREAD

**Issue by jacobg** [googleapis/nodejs-logging-winston#418]
I received an email about GCP deprecation of activity logs, in favor of audit logs. It says a way to identify whether a project is using the legacy activity logs is to look for the `jsonPayload` log field. `nodejs-logging-winston` indeed uses that log field. Does this project need to update for that?

https://cloud.google.com/compute/docs/logging/migrating-from-activity-logs-to-audit-logs

**Comment by bcoe** [comment]
@soldair do you know who we should route this question to?

**Comment by soldair** [comment]
I don't think gcp audit logs have anything to do with this logging api.
In general they can contact cloud support if they have any other questions.
