### ISSUE TITLE
specify labels when init logger

### ISSUE THREAD

**Issue by phantomnat** [googleapis/nodejs-logging-winston#42]
Hi Contributors

I need to put the labels when init the logger.
```js
const optsGCPLogging = {
    projectId: process.env.GCP_PROJECT_ID || 'blah-blah',
    logName: 'some-project',
    label: name || 'main',
    labels: {
      name: _package.name,
      version: _package.version,
      env: process.env.NODE_ENV || 'local'
    }
}
const loggingWinston = new LoggingWinston(optsGCPLogging)
```
![screen shot 2561-02-09 at 8](https://user-images.githubusercontent.com/962802/36031228-a1af0634-0ddc-11e8-8833-c3e1a99e4b05.png)

and made the output messages with a label like in console transporter.

```js
logger.info('test stackdrivers log')
```
![screen shot 2561-02-09 at 8 59 25 pm](https://user-images.githubusercontent.com/962802/36031151-5746aaa2-0ddc-11e8-8018-85568e3423f4.png)

What do you guys think?
Can I create a PR?

**Comment by ofrobots** [comment]
Hi @phantomnat, to make sure I understand well: if `labels` are provided to the constructor, they would be merged into the `labels` on every log request. That would allow one to have a default set of labels that are attached on every log.

That seems like a reasonable idea! A pull request would be great!

**Comment by phantomnat** [comment]
Thanks. I created a PR
