### ISSUE TITLE
Broken link to Stackdriver Error Reporting

### ISSUE THREAD

**Issue by techieshark** [googleapis/nodejs-logging-winston#422]
#### Steps to reproduce

  1. View the [README](https://github.com/googleapis/nodejs-logging-winston/blame/c5a598d280d5bea3f4fe110fefd9cb0feb341b22/README.md#L159)
  2. Observe that there appears to be a failed attempt at linking to Stackdriver Error Reporting (presumably the main product page).

<img width="910" alt="image" src="https://user-images.githubusercontent.com/1072292/70381075-6943dd00-1998-11ea-8367-91d8df98a8b4.png">

**Comment by bcoe** [comment]
thanks for the bug report 👍
