### ISSUE TITLE
README: Missing link to HTTP Request Message reference?

### ISSUE THREAD

**Issue by draperunner** [googleapis/nodejs-logging-winston#453]
I am trying to figure out what properties I can send in the `httpRequest` field. It looks like `[HttpRequest][http-request-message]` part is supposed to be a link, but where to?

<img width="899" alt="image" src="https://user-images.githubusercontent.com/4339443/73645681-06a94d80-4678-11ea-9a98-2806ffcbf3f0.png">

What I want to know specifically is how to log (part of) the request body using this library.

**Comment by draperunner** [comment]
Is this it? https://cloud.google.com/logging/docs/reference/v2/rest/v2/LogEntry#HttpRequest

**Comment by soldair** [comment]
i believe so. how did this work for you?

**Comment by draperunner** [comment]
It answered my questions about what the `httpRequest` can hold. I can submit a PR with a documentation update.

And for reference: I log body parameters simply by passing them as the logger's second argument:
```
logger.info(`Request ${req.method} ${req.url}`, {
    body: req.body,
}
```
