### ISSUE TITLE
customize the logName property using nodejs-logging-winston

### ISSUE THREAD

**Issue by hasanul-murad** [googleapis/nodejs-logging-winston#456]
- When using the NPM package @google-cloud/logging-winston in a Node.JS application hosted on GCP, the Stackdriver logs always appear under the log name “Winston_log” 
- when they are trying to customize the logName property, the logs are lost
- Is it possible to customize the logName property using Winston?

**Comment by soldair** [comment]
the log name changes the log it's written to in stackdriver. The logs should appear but may show up in a non obvious place in the UI.

if you pass {logName:"a_name_here"} in the options
to https://github.com/googleapis/nodejs-logging-winston/blob/master/src/index.ts#L97
it passes the log name to 
https://github.com/googleapis/nodejs-logging-winston/blob/master/src/common.ts#L95
which overrides the defaut value of winston_log.
