### ISSUE TITLE
Allow to make middleware in a sync way 

### ISSUE THREAD

**Issue by bogdan** [googleapis/nodejs-logging-winston#477]
Allow to make middleware in a sync way by manually providing required values that are fetched asyncronously: env and project name.

Async middleware complexes existing application source code and it seems like that data that is obtained asyncronously can be provided manually instead.

**Comment by yaakovfeldman** [comment]
This is obviously a good idea as most express apps are currently sync. (The async main pattern used in the example makes error handling fragile.) It doesn't look like google are interested in providing this, but I point out that the middleware in https://github.com/googleapis/nodejs-logging-winston/blob/main/src/middleware/express.ts is simple enough that you can easily adapt it yourself.

For example, I quickly drafted this adaptation for use in App Engine (not yet fully tested):

```
// copy of https://github.com/googleapis/nodejs-logging-winston/blob/main/src/middleware/express.ts
// with async converted to sync

const { Log, middleware } = require('@google-cloud/logging');
const commonMiddleware = middleware

const REQUEST_LOG_SUFFIX = '_reqlog';
const LOGGING_TRACE_KEY = 'logging.googleapis.com/trace';
const LOGGING_SPAN_KEY = 'logging.googleapis.com/spanId';
const LOGGING_SAMPLED_KEY = 'logging.googleapis.com/trace_sampled';

function makeChildLogger(logger, trace, span, sampled) {
    return logger.child({
        [LOGGING_TRACE_KEY]: trace,
        [LOGGING_SPAN_KEY]: span,
        [LOGGING_SAMPLED_KEY]: sampled,
    });
}

const makeMiddleware = function (logger, projectId, logName) {
    // Unless we are running on Google App Engine or Cloud Functions, generate a
    // parent request log entry that all the request specific logs ("app logs")
    // will nest under. GAE and GCF generate the parent request logs
    // automatically.
    let emitRequestLogEntry;
    if (!process.env.GAE_APPLICATION) {
        // The request logs must have a log name distinct from the app logs
        // for log correlation to work.
        const requestLogName = Log.formatName_(
            projectId,
            `${logName}${REQUEST_LOG_SUFFIX}`
        );
        emitRequestLogEntry = (httpRequest, trace, span, sampled) => logger.info({
            logName: requestLogName,
            [LOGGING_TRACE_KEY]: trace,
            [LOGGING_SPAN_KEY]: span,
            [LOGGING_SAMPLED_KEY]: sampled,
            httpRequest,
            message: httpRequest.requestUrl || 'http request',
        })
    }

    return commonMiddleware.express.makeMiddleware(
        projectId,
        (trace, span, sampled) =>
            makeChildLogger(logger, trace, span, sampled),
        emitRequestLogEntry
    );
}

module.exports = makeMiddleware;
```

Assuming you already have a non middleware Cloud logger set up already you can use it like

```
const loggerMiddleware = require("./logger-middleware");
app.use(loggerMiddleware(logger, 'projectname', 'logname'))
```

**Comment by rileytomasek** [comment]
@losalex would you merge the code above if I opened a PR or is it missing something? Removing the async component will make this much easier to work with.

**Comment by losalex** [comment]
Thank you @rileytomasek for reaching out!
I must admit that I am hesitant to make such a change since it might impact existing customers using async functionality...
Looking into a middleware usage [sample](https://github.com/googleapis/nodejs-logging-winston#using-as-an-express-middleware), it seems that code could be slightly changed so it can be used in non-async way by leveraging `then()` like in example below:

```ts
  const lw = require('@google-cloud/logging-winston');
  const winston = require('winston');
  
  // Import express module and create an http server.
  const express = require('express');
  const logger = winston.createLogger();
  
  const app = express();
  lw.express.makeMiddleware(logger).then((mw: any) => app.use(mw));
```

Please let me know if thats works for you or comment - would really appreciate a feedback.

**Comment by losalex** [comment]
@bogdan / @rileytomasek  / @yaakovfeldman , closing this issue for now - please let me know if my suggestion above works for you and feel free to reopen an issue or comment if you have more suggestions
