### ISSUE TITLE
Loggin has stopped happening on GKE, after cluster upgrad

### ISSUE THREAD

**Issue by vongohren** [googleapis/nodejs-logging-winston#487]
Thanks for stopping by to let us know something could be better!

#### Environment details

  - OS: Linux, docker
  - Node.js version: 10.15
  - npm version:
  - `@google-cloud/logging-winston` version: ^0.8.1
  - Winston: 2.3.3

#### Steps to reproduce

  1. Have a cluster running on GKE with version: 1.15.9-gke.22
  2. Deploy a simple node container with this logging tool in place. That also uses the same version as stated. I don't get any logs into stackdriver anymore. Without any errors, it just ignores that it doesn't work

**Comment by bcoe** [comment]
@vongohren I wonder if you could try running something along the lines of:

```js
// Imports the Google Cloud client library
const {Logging} = require('@google-cloud/logging');

async function quickstart(
  projectId = 'YOUR_PROJECT_ID', // Your Google Cloud Platform project ID
  logName = 'my-log' // The name of the log to write to
) {
  // Creates a client
  const logging = new Logging({projectId});

  // Selects the log to write to
  const log = logging.log(logName);

  // The data to write to the log
  const text = 'Hello, world!';

  // The metadata associated with the entry
  const metadata = {
    resource: {type: 'global'},
    // See: https://cloud.google.com/logging/docs/reference/v2/rest/v2/LogEntry#logseverity
    severity: 'INFO',
  };

  // Prepares a log entry
  const entry = log.entry(metadata, text);

  async function writeLog() {
    // Writes the log entry
    await log.write(entry);
    console.log(`Logged: ${text}`);
  }
  writeLog();
}
```

Inside a container context. I am interested to see if the problem is the logging library itself, or something to do with the winston extension.

**Comment by vongohren** [comment]
@bcoe It was a good attempt, but I actually do believe there is something wrong with my cluster configuration. Becaues nothing is recorded on completely new containers either. I added this and nothing is happening. And I cannot see the error logs from the container either, if there are any. So maybe some fluent stuff has failed. I will close this when I'm solving it

**Comment by vongohren** [comment]
@bcoe this was not related, sorry for the confusion. I had updated my clusters, but not changed this: 
<img width="559" alt="Screenshot 2020-04-01 at 17 26 30" src="https://user-images.githubusercontent.com/1012055/78155586-f2968800-743d-11ea-80e5-6403ecc2217f.png"> to this:
<img width="531" alt="Screenshot 2020-04-01 at 17 27 02" src="https://user-images.githubusercontent.com/1012055/78155635-04782b00-743e-11ea-895e-c2c68cbaebf8.png">

Logs are now showing again

**Comment by bcoe** [comment]
@vongohren awesome, thanks for keeping me in the loop.
