### ISSUE TITLE
Not working with winston 3.0

### ISSUE THREAD

**Issue by pietrofxq** [googleapis/nodejs-logging-winston#49]
Using this library with winston 3.0 throws this error:

```
C:\Users\Pietro Coelho\Desktop\project\backend\node_modules\@google-cloud\logging-winston\build\src\index.js:102
            throw new Error('Unknown log level: ' + levelName);
            ^

Error: Unknown log level: [object Object]
```

Are there plans to support the next version of winston?

**Comment by DominicKramer** [comment]
Thanks for opening this issue.  Yes, we will be supporting the next version of Winston.  At this time, I don't have a timeframe when it will be available.  Out of curiosity, what was the value of `levelName` that you were using that was causing problems?  Thanks.

**Comment by ofrobots** [comment]
It doesn't seem like `winston@3.0` has been released yet. Do we know when it is going to be released?

**Comment by ofrobots** [comment]
Until winston@3 gets released, this is not actionable. I am going to close this.

**Comment by donovanhiland** [comment]
Winston 3.0 is planning to release May 29, 2018.

To provide a little more information about this error @DominicKramer, `levelName` for me is an object that looks like:

```javascript
{
  message: "",
  level: ""
}
```

**Comment by DominicKramer** [comment]
Thanks for letting me know how you are using `levelName`.  I will keep you updated on any status changes.
