### ISSUE TITLE
Logs showing up twice when using the middleware

### ISSUE THREAD

**Issue by zlk89** [googleapis/nodejs-logging-winston#500]
#### Environment details

  - OS: GKE 1.15.9-gke.24
  - Node.js version: v12.14.0
  - npm version: 6.13.4
  - `@google-cloud/logging-winston` version: 3.0.6

#### Steps to reproduce

  1. Just follow steps to create and use the middleware in README
  2. Also using the req.log.info(...) in a few places

<img width="872" alt="Screenshot 2020-04-20 01 46 36" src="https://user-images.githubusercontent.com/7234480/79784306-e85a0200-82f6-11ea-9b25-1108ed69c351.png">
Note that you can see that all related logs are grouped under the "/live" entry correctly, however, those logs are also showing up as separate logs before the "/live" entry.

My guess is that the "/live" entry doesn't emit until the response has sent, so that it knows time spent and payload size.

Do you know how to avoid those duplicate logs, or is it expected?

**Comment by owenconti** [comment]
I'm seeing the exact same problem. Using `@google-cloud/logging-winston` as the only transport, my custom log lines are showing up in GCP Log Viewer twice per line.

**Comment by zlk89** [comment]
I talked to the customer service, the root cause is request log is using different log name

**Comment by owenconti** [comment]
@zlk89 is there anything we can do in user-land to fix in the meantime (other than not use the middleware)?

**Comment by zlk89** [comment]
The root cause is it adds a suffix to the log name https://github.com/googleapis/nodejs-logging-winston/blob/master/src/middleware/express.ts#L69

I guess one workaround is filter by log name

**Comment by eddyoc** [comment]
So... what's the solution?

**Comment by nicoleczhu** [comment]
Hi folks, following up on this issue. 

According to our backend team, this particular case is actually working as intended. We will not resolve this at the API/client library level. 

Logs are not duplicated in storage and only show up as duplicated in the Logs Viewer UI. Internally, there's now a P2 ticket for a UI improvement on this. Thanks for alerting us on it. 

In the meantime, the recommended approach is still to filter for the `*_req` lognames while using the UI. 

I'll update here again when the UI improvement rolls out in the future. 

**Quoting the team:**
```
This is the request correlation feature where if there are two log streams (like `winston_log_reqlog` and `winston_log`), and if the parent request has the httpRequest field (which means its serving a request), and if both parent and child log entries have the same trace-id, the logs viewer correlates the log entries and shows them together.
```

**Comment by samkass** [comment]
I realize this thread is from three years ago, but I got here via a Google search trying to find an answer to this for Cloud Run. It seems to have been already fixed for App Engine and Cloud Functions, but for anyone else landing here and looking for a solution for Cloud Run, the main branch of @google-cloud/logging-winston seems to have a fix for this if you turn on "skipParentEntryForCloudRun" in makeMiddleware (which does not seem to be present even as an option in the v6.0.0 release, so you have to fork/branch and install from git for now):
    // Cloud Run also generates the parent request log automatically, but skipping
    // the parent request entry has to be explicity enabled until the next major
    // release in which we can change the default behavior.
