### ISSUE TITLE
How to use make middleware log to console locally?

### ISSUE THREAD

**Issue by beam36** [googleapis/nodejs-logging-winston#505]
I couldn't figure out how to make middleware log to console locally. The comment in the code example says I should instantiate my own LoggingWinston and pass to makeMiddleware() but how do I configure LoggingWinston to log to console? Can you please help provide an example?

**Comment by rubenvereecken** [comment]
You can indeed pass in your own LoggingWinston instance but if I understand your question correctly that won't make `req.log.info` log locally. Is that what you're after? As far as I know there is no local, "dry-run" mode in LoggingWinston.

If you do want req.log.info available locally without remote calls, here is what I did:
```
	if (isGAE()) {
		app.use(await lwExpress.makeMiddleware(logger));
	} else {
		// Need to stub req.log.info
		app.use((req, res, next) => {
			if (!req.log)
				req.log = {}
			req.log.info = (m, ...args) => {
				logger.info(m, ...args);
			}
		})
	}
```

**Comment by kladnik** [comment]
Is there no better way than this?
This seems very "hacky".

**Comment by losalex** [comment]
@beam36 , really sorry for a late reply, but better later than never - here is recent feature we added to log structured logging to [stdout](https://github.com/googleapis/nodejs-logging-winston#alternative-way-to-ingest-logs-in-google-cloud-managed-environments).

**Comment by losalex** [comment]
Closing this one since there were no response - feel free to reactivate or comment if you need more help
