### ISSUE TITLE
Region is not filled out

### ISSUE THREAD

**Issue by mhaligowski** [googleapis/nodejs-logging-winston#507]
#### Environment details

  - OS: Ubuntu 18.04 @ Google Cloud Function
  - Node.js version: NodeJS 10 @ Google Cloud Function
  - npm version: @ Google Cloud Function
  - `@google-cloud/logging-winston` version: 3.0.6

#### Steps to reproduce

  1. Create default LoggingWinston instance as a transport.
  2. logger.info('Message')
  3. Go to stackdriver console
  4. Look up the log entry
  5. resource.labels.region is "undefined"

As a workaround I'm manually defining the whole resource option.

![Zrzut ekranu 2020-05-23 22 10 10](https://user-images.githubusercontent.com/158472/82746219-33c25e80-9d42-11ea-9002-103e965aba65.png)

**Comment by nicoleczhu** [comment]
Hi @mhaligowski sry for the delay. Region should be filled out now. Thanks!
