### ISSUE TITLE
How does this buffers the log internally?

### ISSUE THREAD

**Issue by arpit728** [googleapis/nodejs-logging-winston#512]
I couldn't find enough documentation on how does this lib. buffers the log internally.
I have the following questions:

1. How much data it buffers internally?
2. How often it makes request to stack-driver server.

I am asking this questions to clarify whether internal buffering can cause any OOM issue.

**Comment by arpit728** [comment]
@JustinBeckwith @yoshi-automation 
Can you help me in figuring this out.

**Comment by bcoe** [comment]
@alexander-fenster am I correct that we buffer logs in gax, so the buffering would most likely be happening in `@google-cloud/logging`.

@arpit728 is there a specific OOM issue that you're running into?

**Comment by alexander-fenster** [comment]
>  am I correct that we buffer logs in gax, so the buffering would most likely be happening in @google-cloud/logging.

Yes, with this configuration: https://github.com/googleapis/nodejs-logging/blob/282036a1ad95d5cfa642022207be6768a5f0f297/src/v2/logging_service_v2_client_config.json#L32-L37

```json
          "bundling": {
            "element_count_threshold": 1000,
            "request_byte_threshold": 1048576,
            "delay_threshold_millis": 50,
            "element_count_limit": 1000000
          }
```

**Comment by nicoleczhu** [comment]
Closing since question is answered & inactive. Feel free to reopen if there are additional followups
