### ISSUE TITLE
Logs Taking Too Long to Appear on Stack Driver.

### ISSUE THREAD

**Issue by arpit728** [googleapis/nodejs-logging-winston#515]
#### Environment details

  - OS: Linux
  - Node.js version: v12.18.1
  - npm version: 6.14.5
  - `@google-cloud/logging-winston` version: ^3.2.1

I created one simple express server which just returns `ok` response, in this request I generate a log. I made 100000 requests to this API.

With this setup it took around 11 mins for all the logs to appear in `stack-driver`.

**Comment by bcoe** [comment]
@arpit728 what environment are you running in, is it a GCP environment such as Google Cloud Functions, or are you testing on your machine.

**Comment by arpit728** [comment]
@bcoe Tested it from both the places, my machine as well as GCP VM.

**Comment by bcoe** [comment]
@arpit728 ultimately log lines do need to make it over the wire to the stack-driver service, so I'm not shocked that there can be a lag if 100,000 requests are made in close succession.

Are you seeing these delays when you write a smaller burst of log lines?

**Comment by arpit728** [comment]
@bcoe If I write just few logs then they appear in just few seconds. In big burst log appears gradually, but it takes too long for all the log entries to appear there.

**Comment by nicoleczhu** [comment]
Closing as this is (unfortunate) but expected behavior
