### ISSUE TITLE
Bump dependency for @google-cloud/logging

### ISSUE THREAD

**Issue by coderholic** [googleapis/nodejs-logging-winston#534]
The latest release depends on @google-cloud/logging 8.0.0, which has broken support for batching, which was fixed in 8.0.4: https://github.com/googleapis/nodejs-logging/releases

The code in this repo now depends on 8.0.5 which includes the fix https://github.com/googleapis/nodejs-logging-winston/blob/master/package.json#L55 - but this hasn't been released to npm as a new version. Npm shows 4.0.0 as 3 months old:

![image](https://user-images.githubusercontent.com/26079/95136864-c412a600-071b-11eb-9fae-52d3ce071d40.png)

Can you do a new release so that people can use this library, and have their logs batched again?

**Comment by coderholic** [comment]
@bcoe any timeline for pushing out a new release (that's all is needed here)?

**Comment by bcoe** [comment]
@coderholic we have the dependency set to `^8.0.5` so a fresh installation will pull in `8.x.x`. We do not generally release new updates for `patches` or `minors`, as they'll be pulled in by the `^` resolution.

**Comment by coderholic** [comment]
@bcoe yeah you're right. removed and re-added:

```
├─ @google-cloud/logging-winston@4.0.0
├─ @google-cloud/logging@8.0.8
```

Sorry, had mis-remembered `^` as pinning to the exact version!
