### ISSUE TITLE
Heads up: logging on kubernetes broken in @google-cloud/logging 1.1.2

### ISSUE THREAD

**Issue by Cory-Simon** [googleapis/nodejs-logging-winston#54]
h/t @bkw googleapis/nodejs-logging-bunyan#31

Lot's of discussion at @google-cloud/logging:
googleapis/nodejs-logging#53
googleapis/nodejs-logging#68
googleapis/nodejs-logging#78

**Comment by laanuk** [comment]
Shit thanks, been grinding at this a while lol

**Comment by aasmm7x** [comment]
Same problem here! Can't log anything when running inside docker container using minikube. Any news about that ? When I run the process in my machine everything is logged normally.

**Comment by ofrobots** [comment]
Folks, the issue in `@google-cloud/nodejs-logging` has been fixed via https://github.com/googleapis/nodejs-logging/pull/81 and released via `v1.1.5` of that library. That version should get picked up when you reinstall your node_modules. Please give that a short and report back if there are still issues. Thanks!

**Comment by Cory-Simon** [comment]
`@google-cloud/nodejs-logging` fixed the issue for us. https://github.com/googleapis/nodejs-logging/pull/88

**Comment by aasmm7x** [comment]
I have updated, but looks like that keeps not logging. I need to setup anything more cause i'm using Kubernetes Engine ?

**Comment by Cory-Simon** [comment]
@aasmm7x Are you sure you have the permissions set correctly? Are you running in a GCP environment?

**Comment by aasmm7x** [comment]
Yes, I'm running an Kubernetes Cluster in GCP. The cluster have those permissions:

Stackdriver Logging API - Write Only
Stackdriver Monitoring API - Full

**Comment by aasmm7x** [comment]
Actually it's working!  🎉

It was my mistake. I was looking on `Stackdriver Logs` in my GCP on the `Global` scope, and not on the `GKE Cluster` scope!

**Comment by ofrobots** [comment]
Glad this is working again! I am going to close this issue.
