### ISSUE TITLE
Why winston logging with Google Cloud Functions requires this lib?

### ISSUE THREAD

**Issue by hixus** [googleapis/nodejs-logging-winston#56]
Why this lib is needed to get Winston to log anything with Google Cloud Functions and what it does differently? Normal console.log works fine, but why regular Winston console transport is not sufficient?

Also in AWS lambda regular console transport works as expected.

**Comment by ofrobots** [comment]
This library should not be necessary on GCF, unless you want custom control over logging (e.g. report logs against a central project name, or customize the log stream destination etc.). Anything printed to the console on GCF gets redirected to Stackdriver Logging automatically, although it would be in a slightly different entry in the tree of categories you see in the Stackdriver Logging UI.

Let us know if this is not working for you, and we can put you in touch with the support folks for GCF. Thanks!

**Comment by ofrobots** [comment]
I believe the question has been addressed, so I am going to close this issue. If this is a mistake, please add a commend and we can reopen the issue.

**Comment by hixus** [comment]
Yes it's resolved. The reason why Winston console transport does not work with google cloud functions is that it uses process.stdout.write instead of console.log. Process.stdout.write does not show in logs.

**Comment by hjaurum** [comment]
winston console and console.log both use stdout.write, what's the difference?
