### ISSUE TITLE
Does not work without setting __dirname to true in webpack config output

### ISSUE THREAD

**Issue by juliushuck** [googleapis/nodejs-logging-winston#563]
#### Environment details

  - OS: MacOs
  - Node.js version: v14.15.5
  - npm version: 6.14.11
  - `@google-cloud/logging-winston` version: 4.0.4

#### Problem

I have to add

```
  node: {
    __dirname: true,
  },
```

to my webpack.config.js. Otherwise I get this in the logs:

![Screen Shot 2021-02-28 at 22 10 59](https://user-images.githubusercontent.com/41862965/109433704-0bbf0480-7a12-11eb-8a65-b7af9f3efcc9.png)

Without the google Winston package i do not have to add the __dirname: true and it works fine.

The problem is, that when i set it to true in webpack, some parts of my code which are using __dirname behave wrong. Is there a way to fix that? Because no other package I use is needing this.

Maybe I'm missing something here, because I'm new to Google Cloud but I read the docs and I did not find something about the __dirname.

**Comment by nicoleczhu** [comment]
Hi @juliushuck , from your error logs, your issue doesn't seem to be related to this library. The specific GCP service you are using is having trouble with your project configuration. You shouldn't have to configure any  `__dirname` to just use this library. 

To wire up Winston with your JS app, you can follow this [quickstart](https://cloud.google.com/logging/docs/samples/logging-winston-quickstart).

If you are using express and want to use the middleware features in this library, you can checkout this [test example](https://github.com/googleapis/nodejs-logging-winston/blob/master/system-test/test-middleware-express.ts).  Here's an [express example with Bunyan](https://cloud.google.com/logging/docs/samples/logging-bunyan-express), which is also very similar to the instrumentation for this lib.

Let me know if the above helps. If not, please create a ticket with specific steps to reproduce our issue: 
- code snippet
- your GCP env (functions? app engine? gke?)
- a longer error log dump
