### ISSUE TITLE
Cloud run environment not being auto detected

### ISSUE THREAD

**Issue by olssonoskar** [googleapis/nodejs-logging-winston#567]
- `@google-cloud/logging-winston` version: 4.0.4
  - `winston`: 3.2.1

Deploying to cloud run with the sample setup fails to provide autodetection of resource.
Instead of being set as a cloud_run_revision as expected, with proper labels, it is being identified as a gce_instance.
Similar comments can be found in: https://github.com/googleapis/nodejs-logging-winston/issues/354
As suggested in issue, one can work around this issue by setting the resource object explicitly. 

Unlcear if this is supported or not but as nothing else is mentioned, and we are running inside GCP, I expect that setting the resource labels should not be required and instead be detected for us. 

Thanks in advance for any additional info about the issue.

**Comment by nicoleczhu** [comment]
This will be supported after environment tests are added [here](https://github.com/googleapis/nodejs-logging-winston/issues/568). 

I just added the tests for Cloud Functions, will do it for Run next. And then the last step is to simply detect the resource data at the client library level for you

**Comment by olssonoskar** [comment]
I see, great to hear that it is in progress and thank you for the quick response. 
Any timeline or release that you think this support can be expected in? 
Either way we will stick to setting it explicitly for now and await further updates here.

**Comment by nicoleczhu** [comment]
It depends on fit it gets flagged as a breaking change/major release or not. If it's a minor release, I estimate ~2 weeks. If it's breaking, it might be longer as we need to bundle those up to max twice per year. Will keep you posted here.

**Comment by nicoleczhu** [comment]
Closing issue as the PR is merged now. release should come out this week as a minor update.
