### ISSUE TITLE
Provide an option to act as `Console` transport using output from `Entry.toJSON`

### ISSUE THREAD

**Issue by ejose19** [googleapis/nodejs-logging-winston#569]
**Is your feature request related to a problem? Please describe.**
When logging in context of `cloud functions`, `cloud run`, `gke` or `gce`, it's often desirable to just output to `stdout` or `stderr` to have the log entries automatically registered. It would be great if this library allowed to JUST output to `stdout`/`stderr`, behaving like a `Console` transport, but formatting to JSON as expected by the api. 

This should allow users to reuse all the parsing/formatting/typings that `@google-cloud/logging` offers, without implementing a custom `Transporter` or `Formatted`.

 **Describe the solution you'd like**
An option while instantiating this library, which when enabled would just print the JSON string and skip the stackdriver call.

 **Describe alternatives you've considered**
Using a custom `transport`, `formatter` or passing the JSON formatted string to a `Console` transport.

**Comment by JCMais** [comment]
+1 for having this feature.

@ejose19 have you decided to use a custom transporter or are you still using this library? which creates a custom log

**Comment by losalex** [comment]
Thanks a lot for opening this issue and really sorry for it took some time to support. I believe the [676](https://github.com/googleapis/nodejs-logging-winston/pull/676) is addressing this issue - please take a look and let me know if this fix addressing your needs. Closing this issue for now - feel free to comment.
