### ISSUE TITLE
Permission denied using default service account

### ISSUE THREAD

**Issue by austonpramodh** [googleapis/nodejs-logging-winston#572]
Hello,
I am facing errors with the default credentials when initializing the `LoggingWinston` inside GKE.

Logs:
```
(node:24) UnhandledPromiseRejectionWarning: Error: 7 PERMISSION_DENIED: The caller does not have permission
    at Object.callErrorFromStatus (/app/node_modules/@grpc/grpc-js/build/src/call.js:31:26)
    at Object.onReceiveStatus (/app/node_modules/@grpc/grpc-js/build/src/client.js:176:52)
    at Object.onReceiveStatus (/app/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:336:141)
    at Object.onReceiveStatus (/app/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:299:181)
    at /app/node_modules/@grpc/grpc-js/build/src/call-stream.js:145:78
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
(node:24) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 11)
```

Initially, I thought the pod doesn't have permissions. I tried running the curl metadata server inside the pod and I got the following response:
```
/app # curl http://169.254.169.254/computeMetadata/v1/instance/service-accounts/default/scopes -H "Metadata-Flavor:Google"
https://www.googleapis.com/auth/devstorage.read_only
https://www.googleapis.com/auth/logging.write
https://www.googleapis.com/auth/monitoring
https://www.googleapis.com/auth/servicecontrol
https://www.googleapis.com/auth/service.management.readonly
https://www.googleapis.com/auth/trace.append
```

I am unable to find a solution, please help.

**Comment by nicoleczhu** [comment]
Hi, by the time you ssh into the pod and ping metadata server, it is ready. 

The race condition happens in the split seconds during the initial deployment, when the library is initially trying to authenticate. The GCP metadata service might not be available to the pods within the first n seconds of deployment.

Please see the troubleshooting guide or next steps mentioned in [this previous issue](https://github.com/googleapis/nodejs-logging-winston/issues/566#issuecomment-814455411). 

Closing as this error doesn't originate from this repo.

**Comment by austonpramodh** [comment]
Thank you so much. 

I just added a 5-sec delay before the server started.

**Comment by austonpramodh** [comment]
Hello,
I added a 30-sec delay before the application starts.  Still no luck.

**Comment by austonpramodh** [comment]
Hi, 
I added a function to wait for the GCP Meta service to start before starting the server.

I am trying to get the token and the scope before I start the server.

Logs:
```
Booting App
Contacting GCP Meta Server
GCP Meta Server responded -  {
  token: {
    access_token: 'ya29.c.KpkB-gcYLx5ltaepfoP4JbHDWUabgif4u40UAWKz9kr-I5dBmbc4_fcXx65wEtb0HQoKIYnjrUPWF0Bg6uFqA5SH-zfwfrlktdYNYgtOXKtkJuv-9jveOZDZQv4bmNjO0-ndV4-y41dwKDdnUhIIUzivfNzl7Dnj5Eke0gt9BCTifCJzXxJuhXNbGZUUjVp5CGOK31SIEbEMHnGF',
    expires_in: 2566,
    token_type: 'Bearer'
  },
  scope: 'https://www.googleapis.com/auth/devstorage.read_only\n' +
    'https://www.googleapis.com/auth/logging.write\n' +
    'https://www.googleapis.com/auth/monitoring\n' +
    'https://www.googleapis.com/auth/servicecontrol\n' +
    'https://www.googleapis.com/auth/service.management.readonly\n' +
    'https://www.googleapis.com/auth/trace.append\n'
}
Using Google Logging
Using local console logging
[NestWinston] Info      4/7/2021, 9:18:07 AM [NestFactory] Starting Nest application... - {}
[NestWinston] Info      4/7/2021, 9:18:07 AM [InstanceLoader] AppModule dependencies initialized - {}
[NestWinston] Info      4/7/2021, 9:18:07 AM [InstanceLoader] PrismaModule dependencies initialized - {}
[NestWinston] Info      4/7/2021, 9:18:07 AM [InstanceLoader] FirebaseModule dependencies initialized - {}
[NestWinston] Info      4/7/2021, 9:18:07 AM [InstanceLoader] HttpModule dependencies initialized - {}
[NestWinston] Info      4/7/2021, 9:18:07 AM [InstanceLoader] DiscoveryModule dependencies initialized - {}
[NestWinston] Info      4/7/2021, 9:18:07 AM [InstanceLoader] CommonModule dependencies initialized - {}
[NestWinston] Info      4/7/2021, 9:18:07 AM [InstanceLoader] ConfigHostModule dependencies initialized - {}
[NestWinston] Info      4/7/2021, 9:18:07 AM [InstanceLoader] TerminusModule dependencies initialized - {}
[NestWinston] Info      4/7/2021, 9:18:07 AM [InstanceLoader] ScheduleModule dependencies initialized - {}
[NestWinston] Info      4/7/2021, 9:18:07 AM [InstanceLoader] ConfigModule dependencies initialized - {}
[NestWinston] Info      4/7/2021, 9:18:07 AM [InstanceLoader] TeachersModule dependencies initialized - {}
[NestWinston] Info      4/7/2021, 9:18:07 AM [InstanceLoader] HealthModule dependencies initialized - {}
[NestWinston] Info      4/7/2021, 9:18:08 AM [RoutesResolver] TeachersController {/teachers}: - {}
[NestWinston] Info      4/7/2021, 9:18:08 AM [RouterExplorer] Mapped {/teachers/assignedNumbers/:id, GET} route - {}
[NestWinston] Info      4/7/2021, 9:18:08 AM [RouterExplorer] Mapped {/teachers/assignPushNotifications, GET} route - {}
[NestWinston] Info      4/7/2021, 9:18:10 AM [RouterExplorer] Mapped {/teachers/create, POST} route - {}
[NestWinston] Info      4/7/2021, 9:18:10 AM [RouterExplorer] Mapped {/teachers/updateDeliveryStatus, PUT} route - {}
[NestWinston] Info      4/7/2021, 9:18:10 AM [RouterExplorer] Mapped {/teachers/message/create, POST} route - {}
[NestWinston] Info      4/7/2021, 9:18:10 AM [RouterExplorer] Mapped {/teachers/message/update, PUT} route - {}
[NestWinston] Info      4/7/2021, 9:18:10 AM [RouterExplorer] Mapped {/teachers/disableDevice/:id, PUT} route - {}
[NestWinston] Info      4/7/2021, 9:18:10 AM [RoutesResolver] HealthController {/health}: - {}
[NestWinston] Info      4/7/2021, 9:18:10 AM [RouterExplorer] Mapped {/health, GET} route - {}
[NestWinston] Info      4/7/2021, 9:18:10 AM [RoutesResolver] CommonController {/common}: - {}
[NestWinston] Info      4/7/2021, 9:18:10 AM [RouterExplorer] Mapped {/common/service-version, GET} route - {}
[NestWinston] Info      4/7/2021, 9:18:10 AM [NestApplication] Nest application successfully started - {}
(node:17) UnhandledPromiseRejectionWarning: Error: 7 PERMISSION_DENIED: The caller does not have permission
    at Object.callErrorFromStatus (/app/node_modules/@grpc/grpc-js/build/src/call.js:31:26)
    at Object.onReceiveStatus (/app/node_modules/@grpc/grpc-js/build/src/client.js:176:52)
    at Object.onReceiveStatus (/app/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:336:141)
    at Object.onReceiveStatus (/app/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:299:181)
    at /app/node_modules/@grpc/grpc-js/build/src/call-stream.js:145:78
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:17) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:17) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by kalantelus** [comment]
@austin

> Hi,
> I added a function to wait for the GCP Meta service to start before starting the server.
> 
> I am trying to get the token and the scope before I start the server.
> 
> Logs:
> 
> ```
> Booting App
> Contacting GCP Meta Server
> GCP Meta Server responded -  {
>   token: {
>     access_token: 'ya29.c.KpkB-gcYLx5ltaepfoP4JbHDWUabgif4u40UAWKz9kr-I5dBmbc4_fcXx65wEtb0HQoKIYnjrUPWF0Bg6uFqA5SH-zfwfrlktdYNYgtOXKtkJuv-9jveOZDZQv4bmNjO0-ndV4-y41dwKDdnUhIIUzivfNzl7Dnj5Eke0gt9BCTifCJzXxJuhXNbGZUUjVp5CGOK31SIEbEMHnGF',
>     expires_in: 2566,
>     token_type: 'Bearer'
>   },
>   scope: 'https://www.googleapis.com/auth/devstorage.read_only\n' +
>     'https://www.googleapis.com/auth/logging.write\n' +
>     'https://www.googleapis.com/auth/monitoring\n' +
>     'https://www.googleapis.com/auth/servicecontrol\n' +
>     'https://www.googleapis.com/auth/service.management.readonly\n' +
>     'https://www.googleapis.com/auth/trace.append\n'
> }
> Using Google Logging
> Using local console logging
> [NestWinston] Info      4/7/2021, 9:18:07 AM [NestFactory] Starting Nest application... - {}
> [NestWinston] Info      4/7/2021, 9:18:07 AM [InstanceLoader] AppModule dependencies initialized - {}
> [NestWinston] Info      4/7/2021, 9:18:07 AM [InstanceLoader] PrismaModule dependencies initialized - {}
> [NestWinston] Info      4/7/2021, 9:18:07 AM [InstanceLoader] FirebaseModule dependencies initialized - {}
> [NestWinston] Info      4/7/2021, 9:18:07 AM [InstanceLoader] HttpModule dependencies initialized - {}
> [NestWinston] Info      4/7/2021, 9:18:07 AM [InstanceLoader] DiscoveryModule dependencies initialized - {}
> [NestWinston] Info      4/7/2021, 9:18:07 AM [InstanceLoader] CommonModule dependencies initialized - {}
> [NestWinston] Info      4/7/2021, 9:18:07 AM [InstanceLoader] ConfigHostModule dependencies initialized - {}
> [NestWinston] Info      4/7/2021, 9:18:07 AM [InstanceLoader] TerminusModule dependencies initialized - {}
> [NestWinston] Info      4/7/2021, 9:18:07 AM [InstanceLoader] ScheduleModule dependencies initialized - {}
> [NestWinston] Info      4/7/2021, 9:18:07 AM [InstanceLoader] ConfigModule dependencies initialized - {}
> [NestWinston] Info      4/7/2021, 9:18:07 AM [InstanceLoader] TeachersModule dependencies initialized - {}
> [NestWinston] Info      4/7/2021, 9:18:07 AM [InstanceLoader] HealthModule dependencies initialized - {}
> [NestWinston] Info      4/7/2021, 9:18:08 AM [RoutesResolver] TeachersController {/teachers}: - {}
> [NestWinston] Info      4/7/2021, 9:18:08 AM [RouterExplorer] Mapped {/teachers/assignedNumbers/:id, GET} route - {}
> [NestWinston] Info      4/7/2021, 9:18:08 AM [RouterExplorer] Mapped {/teachers/assignPushNotifications, GET} route - {}
> [NestWinston] Info      4/7/2021, 9:18:10 AM [RouterExplorer] Mapped {/teachers/create, POST} route - {}
> [NestWinston] Info      4/7/2021, 9:18:10 AM [RouterExplorer] Mapped {/teachers/updateDeliveryStatus, PUT} route - {}
> [NestWinston] Info      4/7/2021, 9:18:10 AM [RouterExplorer] Mapped {/teachers/message/create, POST} route - {}
> [NestWinston] Info      4/7/2021, 9:18:10 AM [RouterExplorer] Mapped {/teachers/message/update, PUT} route - {}
> [NestWinston] Info      4/7/2021, 9:18:10 AM [RouterExplorer] Mapped {/teachers/disableDevice/:id, PUT} route - {}
> [NestWinston] Info      4/7/2021, 9:18:10 AM [RoutesResolver] HealthController {/health}: - {}
> [NestWinston] Info      4/7/2021, 9:18:10 AM [RouterExplorer] Mapped {/health, GET} route - {}
> [NestWinston] Info      4/7/2021, 9:18:10 AM [RoutesResolver] CommonController {/common}: - {}
> [NestWinston] Info      4/7/2021, 9:18:10 AM [RouterExplorer] Mapped {/common/service-version, GET} route - {}
> [NestWinston] Info      4/7/2021, 9:18:10 AM [NestApplication] Nest application successfully started - {}
> (node:17) UnhandledPromiseRejectionWarning: Error: 7 PERMISSION_DENIED: The caller does not have permission
>     at Object.callErrorFromStatus (/app/node_modules/@grpc/grpc-js/build/src/call.js:31:26)
>     at Object.onReceiveStatus (/app/node_modules/@grpc/grpc-js/build/src/client.js:176:52)
>     at Object.onReceiveStatus (/app/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:336:141)
>     at Object.onReceiveStatus (/app/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:299:181)
>     at /app/node_modules/@grpc/grpc-js/build/src/call-stream.js:145:78
>     at processTicksAndRejections (internal/process/task_queues.js:75:11)
> (Use `node --trace-warnings ...` to show where the warning was created)
> (node:17) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
> (node:17) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> ```

Were you able to get a fix for this? Running into the same issue

**Comment by aroman** [comment]
I'm also running into this. My service account definitely has the `Error Reporting Writer` permission...
