### ISSUE TITLE
GCP logger always shows "info" icon

### ISSUE THREAD

**Issue by jonbcampos-alto** [googleapis/nodejs-logging-winston#643]
#### Environment details

  - OS: Linux
  - Node.js version: 10-alpine (docker)
  - npm version: 6.14.11
  - `@google-cloud/logging-winston` version: ^4.0.2

#### Steps to reproduce

  1. create logger

```
const transports = [
    // Log to the console
    new winston.transports.Console(),
		new LoggingWinston()
  ];
  const logger = winston.createLogger({
    level: setting.logLevel, // log at info and above
    format: format.combine(winston.format.json()),
    transports,
  });
```

  2. log something that isn't "info" type

```
logger.warn("I am from v2!");
```

3. see that GCP shows it as info

<img width="681" alt="Screen Shot 2021-12-09 at 7 26 00 PM" src="https://user-images.githubusercontent.com/43216158/145588528-672a5be7-088c-4a98-a782-64fa30f72383.png">

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

I'm sure I'm missing something, but it is so easy that I'm not sure what. I've tried looking in other tickets but can't find anything.

**Comment by jonbcampos-alto** [comment]
You are right. Last night as I took another crack at it I figured out that
the project I was testing with had a conflicting and older version of
Winston that seemed to get in the way. I was trying to narrow it down
before closing this but I think that fixed it. I think it is just a version
issue for me.

**Comment by losalex** [comment]
Thank you @jonbcampos-alto for checking this!
