### ISSUE TITLE
Express middleware set response codes > 500 in error level

### ISSUE THREAD

**Issue by ElMatella** [googleapis/nodejs-logging-winston#658]
Hi, I'm using this awesome library for my projects using expressJS.

Do you know if I can set error log level on entries where response code is greater or equel to 500? When using Cloud run it does that automatically, but not when using the express middleware. All my entries are logged as info level. 

Thank you very much for your responses.

Here is how I initiate the express middleware:

    const loggerMw = await express.makeMiddleware(
      createLogger({
        level: 'debug',
      }),
      {
        projectId: 'xxxxx',
        labels: {
          service_name: 'xxxx'
        }
      }
    );

**Comment by ElMatella** [comment]
https://github.com/googleapis/nodejs-logging-winston/blob/504bb6fb0fd461a826af7f6a6b36806328bf72e8/src/middleware/express.ts#L90-L99

Ho well, this happens around here. I assume that changing this behaviour would change too much of a thing for some people... Maybe this could be optional?

**Comment by minherz** [comment]
hi,
thank you for your question. as you mentioned, there is no easy way to customize the behavior of the winston adapter for google cloud logging. We will look for options and get back to you.

**Comment by losalex** [comment]
I will close this issue since it is not critical to fix - please let me know if anyone thinks otherwise.
