### ISSUE TITLE
Update dependency @google-cloud/logging from 9.0.0 to 9.6.9

### ISSUE THREAD

**Issue by toninofox** [googleapis/nodejs-logging-winston#666]
1) Is this a client library issue or a product issue?
This is the client library issue for google-logging
 "GoogleError: Total timeout of API google.logging.v2.LoggingServiceV2 exceeded 60000 milliseconds before any response was received"
https://github.com/googleapis/nodejs-logging/issues/1185

2) Did someone already solve this?
Error has been fixed to @google-cloud/logging version 9.6.9 
https://github.com/googleapis/nodejs-logging/pull/1225

**Comment by losalex** [comment]
@toninofox ,
Thanks a lot for filing this issue! Based on my explanation in [#1225](https://github.com/googleapis/nodejs-logging/pull/1225), the solution was to provide an ability to add a global callback which could be used to catch errors and prevent a crash. As of timeouts - I believe those still can happen and each individual case might have different reasons to get a timeout. Thats said, if there is strong indication that timeouts are increased dramatically in same runtime environment simply after logging library package update, we can definitely look into such case separately.
