### ISSUE TITLE
`labels` option is an invalid type on TypeScript environment.

### ISSUE THREAD

**Issue by aasmm7x** [googleapis/nodejs-logging-winston#67]
I'm having problem with the package typings. Looks like that the 'labels' options is missing in type.

I'm getting  `**Object literal may only specify known properties, and 'labels' does not exist in type 'Options | undefined'.**`

#### Environment details

  - OS: Mac OS X
  - Node.js version: 8.9.4
  - npm version: 5.7.1
  - `@google-cloud/logging-winston` version: 0.8.1

#### Steps to reproduce

  1. Be on an TypeScript strict environment.
  2. Create an transport with new LoggingWinston({ labels: { 'key': 'value' } })

**Comment by aasmm7x** [comment]
Why I don't see any fix in the commit ? Shows only the version bump.

**Comment by DominicKramer** [comment]
Version 0.9.0 has been released that should address this issue.  If you still having issues, please let me know.  Thanks.
