### ISSUE TITLE
Express middleware does not correlate log with traces

### ISSUE THREAD

**Issue by jRichardeau** [googleapis/nodejs-logging-winston#674]
Hello,

I'm using `@google-cloud/logging-winston` and the `express` middleware for logging purpose.
I want to to add tracing infos in my project using `@google-cloud/trace-agent`.

The two modules are working well but I can't have correlation between my traces and my logs, they are using a different trace id.

See this GCP screenshots : 

![image](https://user-images.githubusercontent.com/4921182/158552748-7f1bf373-f3db-48c2-a0a9-57a0b93ce043.png)

![image](https://user-images.githubusercontent.com/4921182/158552797-f5f9c2a2-aa93-450e-b325-4559ad5a61bf.png)

#### Environment details

  - OS: Mac OS 12.2.1
  - Node.js version: 12.22.7
  - npm version: 6.14.15
  - `@google-cloud/logging-winston` version: 4.1.3
  - `@google-cloud/trace-agent`: 5.1.6
  - `express`: 4.17.3,
  - `winston`: 3.6.0

#### Steps to reproduce

  1. Create an `express` application.
  2. Use `@google-cloud/logging-winston` middleware for `express`
  3. Add `require('@google-cloud/trace-agent').start()` as first instruction.
  
#### Example code that doesn't work

```js
require('@google-cloud/trace-agent').start();

const express = require('express')
const winston = require('winston');
const lw = require('@google-cloud/logging-winston');
const port = 3000

const logger = winston.createLogger();

async function init() {
  const mw = await lw.express.makeMiddleware(logger);

  const app = express()
  app.use(mw);

  app.get('/hello', (req, res) => {
    req.log.info('Hello');
    res.send('Hello World!')
  });

  app.listen(port, () => {
    console.log(`Example app listening on port ${port}`)
  });
}

init();

```

Thank you for your help

**Comment by jeremiewtd** [comment]
Hi!
Any news about this ? Is this a real bug ?
Thanks

**Comment by jRichardeau** [comment]
Hi!
Any news about this ? Is this a real bug ?
Thanks

**Comment by jRichardeau** [comment]
I think I found the answer looking at the code, it doesn't seem to work since `winston 3`, so I'm using the function created in #388 like this :

```js
const winston = require('winston');
const lw = require('@google-cloud/logging-winston');

const logger = winston.createLogger({
  defaultMeta: lw.getDefaultMetadataForTracing()
});

...

const mw = await lw.express.makeMiddleware(logger);

const app = express()
app.use(mw);
```

This correlates my traces and logs !

Is this the right way to do it ?

Thank you
