### ISSUE TITLE
Stackdriver not logging in Logger when is provided a metadata.

### ISSUE THREAD

**Issue by aasmm7x** [googleapis/nodejs-logging-winston#70]
#### Environment details

  - OS: Mac OS X
  - Node.js version: v8.9.4
  - npm version: 5.7.1
  - `@google-cloud/logging-winston` version: ^0.9.0

#### Steps to reproduce

  1. Try to log an error with metadata.
  2. winstonLogger.info('Some log message', { test: 'value' });

No log is saved on StackDriver Logger Global.

**Comment by DominicKramer** [comment]
Thank you for letting us know about this.  I will be investigating this and will let you know about the progress.

**Comment by aasmm7x** [comment]
I was able to solve the problem! 

Looks like that the time to log entry request complete is a litle longer, and after the log show on terminal console I was finishing the process, making the request to Stackdriver Logging not finish/reach the Stackdriver.

Can close the issue. Thanks.

**Comment by DominicKramer** [comment]
I'm glad you got it working.  Thanks for letting me know.  I'll close the issue.
