### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'nullValue')

### ISSUE THREAD

**Issue by francescov1** [googleapis/nodejs-logging-winston#719]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

1) Is this a client library issue or a product issue?
Client library issue

2) Did someone already solve this?
  - Search the issues already opened: https://github.com/googleapis/nodejs-logging-winston/issues
  - Search the issues on our "catch-all" repository: https://github.com/googleapis/google-cloud-node
  - Search or ask on StackOverflow (engineers monitor these tags): http://stackoverflow.com/questions/tagged/google-cloud-platform+node.js
No

3) Do you have a support contract?
No

#### Environment details

  - OS: node:16.15.0-alpine Docker image
  - Node.js version: 16.15.0
  - npm version: 8.5.5
  - `@google-cloud/logging-winston` version: 4.1.0

#### Steps to reproduce

We are getting a high number of Sentry errors in production reporting an unhandled error from this library: `TypeError: Cannot read properties of undefined (reading 'nullValue')`. I attached a screenshot below showing where the error is being thrown. See [the full Sentry error](https://sentry.io/share/issue/84570c3c33714becab5576f10f25c170/) for more details. Unsure how to reproduce.

<img width="1197" alt="Screen Shot 2022-07-05 at 10 56 26 AM" src="https://user-images.githubusercontent.com/26126685/177357403-70d6e8b7-d6a7-4c6a-8417-6779d40432a1.png">

**Comment by francescov1** [comment]
Any updates on this?

**Comment by losalex** [comment]
> Any updates on this?

@francescov1 , sorry for delayed answer and thanks for your patience. Based on image you shared, seems that error happens in GAX layer which is harder to debug if we missing the overall picture - if there a code snippet you can share how the library is used? Also seems that your `@google-cloud/logging-winston` library version is 4.1.0 - I wonder if it wold be possible to upgrade the library to latest version snd see if error persists.

**Comment by francescov1** [comment]
@losalex Here's the code we are using (and then using the logger object to log messages and errors in our application).

```typescript
import winston from 'winston';
import * as GcpTransport from '@google-cloud/logging-winston';

export const logger = winston.createLogger({
  level: 'info',
  format: winston.format.combine(winston.format.timestamp(), sanitizeLogs()),
  exitOnError: false,
  transports: [
    new GcpTransport.LoggingWinston(), 
    new SentryTransport({ level: 'error' })
  ]
});

```

Will try upgrading

**Comment by francescov1** [comment]
Hi @losalex , we're still seeing this occur after upgrading to the latest version. Is there any other info I can provide? We're getting a large amount of these coming in, and are worried that its causing us to miss critical logs.

**Comment by losalex** [comment]
@francescov1 , sorry for long time it takes to clarify the issue - I am still on it and currently working with our GAX team to get an idea why this issue is happening. Just out of curiosity - would you please be able to remove the `SentryTransport` from code and see if an issue still repro?

**Comment by losalex** [comment]
@francescov1 , would you be able also to add a code which performs logging as well? What kind of methods you use to log entries? After preliminary analysis, it seems this problem might require some effort to debug and apparently as of now we cannot identify exactly what is a problem. Can you please also let me know the environment where logging library is used?

**Comment by francescov1** [comment]
@losalex I am not currently active on this project anymore, @lncramer can you take this over?

**Comment by losalex** [comment]
Thank you @francescov1 for an update! 
Can I ask you to update to latest `nodejs-logging-winston` library? My latest update [733](https://github.com/googleapis/nodejs-logging-winston/pull/733) contains a GAX fix which will print to `stderr` failing payload which could be useful to understand a failure.

**Comment by losalex** [comment]
Lowering priority - awaiting for input

**Comment by losalex** [comment]
Closing this issue since it seems there are no response. Feel free to comment or reopen per need
