### ISSUE TITLE
logging-winston 5.1.5 dependency on @google-cloud/logging is leading to an error

### ISSUE THREAD

**Issue by somewhatabstract** [googleapis/nodejs-logging-winston#739]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

1) Is this a client library issue or a product issue?
Client library issue. Dependency is unable to find a file it requires.

2) Did someone already solve this?
Cannot find an existing issue/resolution (other than just not updating)

3) Do you have a support contract?
Please create an issue in the [support console](https://cloud.google.com/support/) to ensure a timely response.

If the support paths suggested above still do not result in a resolution, please provide the following details.

#### Environment details

  - OS: MacOS Monterrey 12.5.1 
  - Node.js version: 16.17.0
  - npm version: 8.15.0
  - yarn version: 1.22.18
  - `@google-cloud/logging-winston` version: 5.1.5

#### Steps to reproduce

  1. Add `@google-cloud/logging-winston` as dependency
  2. Import it in a test (or use it in non-test code) - I use jest (repro'd with 28 and 29)
  3. See import error:
  
  ```
  Cannot find module 'google-gax/build/src/protobuf' from 'node_modules/@google-cloud/logging/build/protos/protos.js'

    Require stack:
      node_modules/@google-cloud/logging/build/protos/protos.js
      node_modules/@google-cloud/logging/build/src/index.js
      node_modules/@google-cloud/logging-winston/build/src/common.js
      node_modules/@google-cloud/logging-winston/build/src/index.js
  ```

**Comment by somewhatabstract** [comment]
See https://github.com/Khan/render-gateway/runs/8215698363?check_suite_focus=true for example of issue.

**Comment by losalex** [comment]
@somewhatabstract , can you please update to latest logging-winston library and recompile? Please let me know if thats work for you - if not, can you please share package.json?

**Comment by somewhatabstract** [comment]
@losalex The `package.json` is here: https://github.com/Khan/render-gateway/blob/dependabot/npm_and_yarn/google-cloud/logging-winston-5.1.5/package.json

You can see the failed update in the link above and the associated PR here: https://github.com/Khan/render-gateway/pull/933

**Comment by losalex** [comment]
Oh, thanks @somewhatabstract - my bad, didn't mentioned that PR...
I wonder if you able to compile that change locally - it might be related to some stale references for `@google-cloud/logging`. Can you perhaps try the following command on your Mac and recompile afterwards:

`rm -rf package-lock.json node_modules && npm install`

**Comment by somewhatabstract** [comment]
Yes! We're using `yarn` so I ran this:

```
rm -rf node_modules yarn.lock && yarn
```

And that fixed things!

**Comment by losalex** [comment]
Ah, awesome - thank you for letting me know @somewhatabstract !
Is there anything else I can help with? I wonder if we can close the case :-)

**Comment by somewhatabstract** [comment]
Yes, I think this can be closed. Thank you for your assistance!

**Comment by losalex** [comment]
> Yes, I think this can be closed. Thank you for your assistance!

The pleasure is mine - thank you!
