### ISSUE TITLE
Using this library with Webpack and yarn PnP results in build warnings

### ISSUE THREAD

**Issue by dzbarsky** [googleapis/nodejs-logging-winston#762]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

#### Environment details

  - OS: mac
  - Node.js version: 16.x
  - npm version:
  - `@google-cloud/logging-winston` version: 5.1.3

#### Steps to reproduce

  1. Use project in webpack or next build with yarn pnp
  2. Note warning:
```
../../../.yarn/__virtual__/@google-cloud-logging-winston-virtual-bfe17c7235/0/cache/@google-cloud-logging-winston-npm-5.1.5-9bf0067665-24b9d19918.zip/node_modules/@google-cloud/logging-winston/build/src/common.js
Critical dependency: the request of a dependency is an expression

Import trace for requested module:
../../../.yarn/__virtual__/@google-cloud-logging-winston-virtual-bfe17c7235/0/cache/@google-cloud-logging-winston-npm-5.1.5-9bf0067665-24b9d19918.zip/node_modules/@google-cloud/logging-winston/build/src/common.js
../../../.yarn/__virtual__/@google-cloud-logging-winston-virtual-bfe17c7235/0/cache/@google-cloud-logging-winston-npm-5.1.5-9bf0067665-24b9d19918.zip/node_modules/@google-cloud/logging-winston/build/src/index.js

```

https://github.com/googleapis/nodejs-logging-winston/pull/761 has a potential fix

**Comment by daniel-sanche** [comment]
According to losalex's [comment here](https://github.com/googleapis/nodejs-logging-winston/pull/761#pullrequestreview-1169245477), this should be fixed by https://github.com/googleapis/nodejs-logging-winston/pull/763 and https://github.com/googleapis/nodejs-logging-winston/pull/760, which have both been merged.

Feel free to re-open if you're still seeing this issue though
