### ISSUE TITLE
How can I set the individual format for transports?

### ISSUE THREAD

**Issue by anselmo-coolstay** [googleapis/nodejs-logging-winston#772]
My application needs two transports. One is for Cloud Logging and the other is for console.
Both transports should have different formats.

According to https://github.com/winstonjs/winston#common-transport-options, Winston support the format for a transport.
But, the options for LoggingWinston's constructor seems not to support it.

How can I set them differently?

**Comment by losalex** [comment]
Thanks @anselmo-coolstay - indeed, this is a feature missing. As a workaround, you could just create multiple loggers with dedicated format by calling `winston.createLogger`, but I agree it is less convenient.
