### ISSUE TITLE
nightly system tests failure

### ISSUE THREAD

**Issue by alexander-fenster** [googleapis/nodejs-logging-winston#78]
We keep having failing nightly tests for logging-winston and it's just kind of ignored, which ruins the whole idea of running continuous integration :)

I suggest that we spend some time this week to make sure we have all green CI in all our libraries. This particular project has only one system test that fails almost all the time:

```
  1) LoggingWinston
       log
         should properly write log entries:

      Uncaught AssertionError [ERR_ASSERTION]: { metadata: { testTimestamp: 'Sat May 05 2018 08:19:11 GMT+0000 (UTC)' },
  message: 'third' } deepStrictEqual { message: 'first', metadata: {} }
      + expected - actual

       {
      -  "message": "third"
      -  "metadata": {
      -    "testTimestamp": "Sat May 05 2018 08:19:11 GMT+0000 (UTC)"
      -  }
      +  "message": "first"
      +  "metadata": {}
       }
```

Let's either fix it (preferred option) or disable it at all until investigated and fixed. I just want to have 0 failures in nightly so that each nightly failure got some kind of investigation and was not ignored (like it happens now).

cc: @ofrobots, @crwilcox

**Comment by ofrobots** [comment]
@alexander-fenster Do you know the frequency of this failure in the nightlies? I am trying to figure out if it is worth trying to reproduce this.

**Comment by ofrobots** [comment]
Failed last night: https://circleci.com/workflow-run/bb5df729-9f3d-410a-8f2b-6cc1609c910e

**Comment by alexander-fenster** [comment]
They fail every day, with rare exceptions.

https://circleci.com/gh/googleapis/workflows/nodejs-logging-winston/tree/master

**Comment by DominicKramer** [comment]
I've tried several times to reproduce the failures locally and on Circle but cannot reproduce them to be able to debug the issue.  @alexander-fenster have you had any success reproducing the failure?

**Comment by ofrobots** [comment]
I cannot reproduce it either. At this point, I need to access the cloud console for the project against which we are running the tests. @alexander-fenster: can you share that info with me privately?

**Comment by ofrobots** [comment]
This is a race condition between the sample tests and system tests. That's why it only flakes on CircleCI.

**Comment by ofrobots** [comment]
Both of them write log entries, and then read them back. Depending on timing they read back each other's logs and complain when they find unexpected things.
