### ISSUE TITLE
adds pointless `projects/{{projectId}}/logs/winston_log` property to logs when `redirectToStdout` is set to `true`

### ISSUE THREAD

**Issue by macrozone** [googleapis/nodejs-logging-winston#785]
#### Environment details

  - OS:
  - Node.js version: 16.19.1
  - npm version: 
  - `@google-cloud/logging-winston` version: 5.3.0

#### Steps to reproduce

1. create the following log:

```

const googleCloudLogger = new LoggingWinston({
  redirectToStdout: true,
})
```

2. deploy to cloud run
3. logs will then look like this:

<img width="784" alt="Bildschirm­foto 2023-02-28 um 15 15 35" src="https://user-images.githubusercontent.com/1972353/221880098-7ae54c76-83b5-438a-a778-850814683970.png">

you notice that it adds an additional logName property `projects/{{projectId}}/logs/winston_log` which adds noise to it and is even the first thing you see and therefore makes it hard to read the logs.

you also see that the real correct logName is also visible one level above

**Comment by fairojm** [comment]
If we use `useMessageField` option set to false then logs are appearing fine in cloud run.

**Comment by pebo** [comment]
> If we use `useMessageField` option set to false then logs are appearing fine in cloud run.
Are you using `redirectToStdout: true`? I get the `logName` added when using:
```javascript
  redirectToStdout: true,
  useMessageField: false,
```

**Comment by cindy-peng** [comment]
Hi @macrozone , could you try [useMessageField](https://github.com/googleapis/nodejs-logging-winston#alternative-way-to-ingest-logs-in-google-cloud-managed-environments) and see if you are still running into this? `useMessageField` is used to control if "message" field is used to store structured, non-text data inside jsonPayload field when redirectToStdout is set.

**Comment by cindy-peng** [comment]
Closing issue as setting`useMessageField` to false will solve the issue here.

**Comment by evil-shrike** [comment]
I'm having the same issue with `useMessageField: false` and `redirectToStdout: true`.
![image](https://github.com/user-attachments/assets/e593c966-616d-4221-8b15-6fd0fc2c6b6c)

**Comment by evil-shrike** [comment]
please re-open
