### ISSUE TITLE
Skip writing RequestLogEntry for Cloud Run

### ISSUE THREAD

**Issue by pebo** [googleapis/nodejs-logging-winston#793]
Cloud Run already adds request logs so with nodejs-logging-winston there's an additional log entry for each request.

The check for `emitRequestLogEntry` currently only checks for cloud functions and app engine. 

https://github.com/googleapis/nodejs-logging-winston/blob/9b8657aa436787591c03717e1111117cda6687ee/src/middleware/express.ts#L83

 **Is your feature request related to a problem? Please describe.**
Request logs are duplicated with incurs uncessary cost and make the logs hard to read.,

 **Describe the solution you'd like**
Add [GCPEnv.CLOUD_RUN](https://github.com/googleapis/google-auth-library-nodejs/blob/85f2c9393f64b97290a0698d3ac6754fa9bc951a/src/auth/envDetect.ts#L22) to the `emitRequestLogEntry` check

 **Describe alternatives you've considered**
-

 **Additional context**
-

**Comment by losalex** [comment]
Thanks @pebo for opening this issue! It seems that proper solution for this problem described in [795](https://github.com/googleapis/nodejs-logging-winston/issues/795), so I will close this one as duplicate.
Please let me know if you have any other concerns.
