### ISSUE TITLE
winston 3.0.0 support

### ISSUE THREAD

**Issue by AntoineMaitre** [googleapis/nodejs-logging-winston#84]
Hi guys, first of all thanks for your amazing work !

Since winston 3.0.0 is being in RC and is planned to be released by the end of this month, I'd like to know what are your plans regarding this new release and the compatibility with your package ?

Thanks in advance for your answers ;)

**Comment by DominicKramer** [comment]
Thanks for opening this issue.  A conversation with the winston developers is happening at winston issue [#1331](https://github.com/winstonjs/winston/issues/1331) to determine the best way the logging-winston library should address the new release.

**Comment by carusology** [comment]
I tried to update a module to winston@3 today and found I couldn't because I depend on this transport to log to Stackdriver. Are you guys getting closer to a ballpark timeline for supporting the new version of winstone? I read [winston#1331](https://github.com/winstonjs/winston/issues/1331) and it does not look like the conversation is en route to any conclusion yet.

**Comment by DominicKramer** [comment]
@carusology Winston 3 support is high on list of things we want to implement, and we'll keep this thread updated with more info as it becomes available.  Thanks

**Comment by chroth7** [comment]
Has there been an update? Sorry for being pushy, but would love to have winston3 - thanks!

**Comment by ofrobots** [comment]
Hi Folks. We haven't been able to get around to this just yet – but we are definitely not ignoring this. There is some thought needed here on whether we want to continue supporting both `winston@2` and `winston@3` out of the same module and if so how that should work. This requires some dedicated time that we haven't been able to find just yet. I am hopeful to start work on this soon though. We'll also take a look at #150. Thanks for your patience.

**Comment by jniemin** [comment]
Is there any plan, when this is going to be released?

**Comment by ofrobots** [comment]
Hi @jniemin. Support for `winston@3` was implemented in #161. We are sorting out some issues in how the system-tests are put together. We'll send this out in a release once those bugs are ironed out.
