### ISSUE TITLE
Adding HTTP request context to an error line does not propagate to context.httpRequest

### ISSUE THREAD

**Issue by priestjim** [googleapis/nodejs-logging-winston#87]
#### Environment details

  - OS: node:8.11.2 docker image
  - Node.js version: 8.11.2
  - npm version: 5.6.0
  - `@google-cloud/logging-winston` version: 0.9.0

#### Steps to reproduce

When dealing with an exception in a context where HTTP request information is available for that error (i.e. within the good reporter for hapi.js), setting metadata.context.httpRequest should make the SD winston transport populate the `context.httpRequest` object within the log request object to provide Error Reporting with more available metadata.

**Comment by DominicKramer** [comment]
Thank you for the feedback.  We'll update this thread with more information as we look into this.

**Comment by ofrobots** [comment]
@priestjim we are not very familiar with how hapi.js provides http request on the error. Can you give us more details?

**Comment by priestjim** [comment]
It's not necessarily relevant to HAPI. When logging an error with an httpRequest object inside the metadata object such as `logger.info('Message', { httRequest: { ... } });`, shouldn't this `httpRequest` object be transferred inside the `context` property of the logged line object to provide HTTP request metadata?

**Comment by ofrobots** [comment]
@priestjim we already do that: https://github.com/googleapis/nodejs-logging-winston/blob/27da687d996fb634e77c5604b6203170f5f74531/src/common.ts#L147-L155.

Let us know if this addresses your need.

**Comment by ofrobots** [comment]
Closing as answered. Please add a comment if this is incorrect.
