### ISSUE TITLE
Adding custom labels to a log will permanently merge them for the logger instance

### ISSUE THREAD

**Issue by arsanjea** [googleapis/nodejs-logging-winston#88]
#### Environment details

  - OS: Ubuntu
  - Node.js version: 8.9.4
  - npm version: 5.6.0
  - `@google-cloud/logging-winston` version: 0.9.0

#### Steps to reproduce

  1. Create new logger instance
```
...
  const loggingWinston = new LoggingWinston({
    labels: {
      label1: 'label1',
    },
  });
....
  const logger = new Logger({
    prefix: 'web-server',
    level: 'info', // log at 'info' and above
    transports: [loggingWinston],
  });
...
```
  2. Log with custom labels
```
logger.info('hello', { message: { prop1: 'test' }, labels: { label2: 'label2' } });
```
  3. Subsequent log without custom labels 
```
logger.info('hello', { message: { prop1: 'test' } });
```
#### Actual result/issue
- The 2nd log (step 3) is recorded with both label 1 and label 2

#### Expected result
- The 1st log (step 2) is recorded in my google cloud logs with the labels: label1 & label2
- The 2nd log (step 3) is recorded in my google cloud logs with the only label1

**Comment by madhu703** [comment]
thank you for your solution
